# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\x0f\x66\x65ishulib.proto\"$\n\x06Header\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\xc7\x01\n\x05\x46rame\x12\x0e\n\x06seq_id\x18\x01 \x02(\x04\x12\x0e\n\x06log_id\x18\x02 \x02(\x04\x12\x0f\n\x07service\x18\x03 \x02(\x05\x12\x0e\n\x06method\x18\x04 \x02(\x05\x12(\n\x07headers\x18\x05 \x03(\x0b\x32\x17.feishulib.proto.Header\x12\x18\n\x10payload_encoding\x18\x06 \x01(\t\x12\x14\n\x0cpayload_type\x18\x07 \x01(\t\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\x12\x12\n\nlog_id_new\x18\t \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=32
  _globals['_HEADER']._serialized_end=68
  _globals['_FRAME']._serialized_start=71
  _globals['_FRAME']._serialized_end=270
# @@protoc_insertion_point(module_scope)
